/* automatically generated by rust-bindgen */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __STDC_NO_THREADS__: u32 = 1;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 27;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const LSL_IRREGULAR_RATE: f64 = 0.0;
pub const LSL_DEDUCED_TIMESTAMP: f64 = -1.0;
pub const LSL_FOREVER: f64 = 32000000.0;
pub const LSL_NO_PREFERENCE: u32 = 0;
pub const LIBLSL_COMPILE_HEADER_VERSION: u32 = 113;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___fsid_t() {
    assert_eq!(
        ::std::mem::size_of::<__fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__fsid_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__fsid_t>())).__val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__fsid_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub const lsl_channel_format_t_cft_float32: lsl_channel_format_t = 1;
pub const lsl_channel_format_t_cft_double64: lsl_channel_format_t = 2;
pub const lsl_channel_format_t_cft_string: lsl_channel_format_t = 3;
pub const lsl_channel_format_t_cft_int32: lsl_channel_format_t = 4;
pub const lsl_channel_format_t_cft_int16: lsl_channel_format_t = 5;
pub const lsl_channel_format_t_cft_int8: lsl_channel_format_t = 6;
pub const lsl_channel_format_t_cft_int64: lsl_channel_format_t = 7;
pub const lsl_channel_format_t_cft_undefined: lsl_channel_format_t = 0;
pub type lsl_channel_format_t = u32;
pub const lsl_processing_options_t_proc_none: lsl_processing_options_t = 0;
pub const lsl_processing_options_t_proc_clocksync: lsl_processing_options_t = 1;
pub const lsl_processing_options_t_proc_dejitter: lsl_processing_options_t = 2;
pub const lsl_processing_options_t_proc_monotonize: lsl_processing_options_t = 4;
pub const lsl_processing_options_t_proc_threadsafe: lsl_processing_options_t = 8;
pub const lsl_processing_options_t_proc_ALL: lsl_processing_options_t = 15;
pub type lsl_processing_options_t = u32;
pub const lsl_error_code_t_lsl_no_error: lsl_error_code_t = 0;
pub const lsl_error_code_t_lsl_timeout_error: lsl_error_code_t = -1;
pub const lsl_error_code_t_lsl_lost_error: lsl_error_code_t = -2;
pub const lsl_error_code_t_lsl_argument_error: lsl_error_code_t = -3;
pub const lsl_error_code_t_lsl_internal_error: lsl_error_code_t = -4;
pub type lsl_error_code_t = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lsl_streaminfo_struct_ {
    _unused: [u8; 0],
}
pub type lsl_streaminfo = *mut lsl_streaminfo_struct_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lsl_outlet_struct_ {
    _unused: [u8; 0],
}
pub type lsl_outlet = *mut lsl_outlet_struct_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lsl_inlet_struct_ {
    _unused: [u8; 0],
}
pub type lsl_inlet = *mut lsl_inlet_struct_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lsl_xml_ptr_struct_ {
    _unused: [u8; 0],
}
pub type lsl_xml_ptr = *mut lsl_xml_ptr_struct_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lsl_continuous_resolver_ {
    _unused: [u8; 0],
}
pub type lsl_continuous_resolver = *mut lsl_continuous_resolver_;
extern "C" {
    pub fn lsl_protocol_version() -> i32;
}
extern "C" {
    pub fn lsl_library_version() -> i32;
}
extern "C" {
    pub fn lsl_library_info() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_local_clock() -> f64;
}
extern "C" {
    pub fn lsl_resolve_all(
        buffer: *mut lsl_streaminfo,
        buffer_elements: u32,
        wait_time: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_resolve_byprop(
        buffer: *mut lsl_streaminfo,
        buffer_elements: u32,
        prop: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        minimum: i32,
        timeout: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_resolve_bypred(
        buffer: *mut lsl_streaminfo,
        buffer_elements: u32,
        pred: *const ::std::os::raw::c_char,
        minimum: i32,
        timeout: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_destroy_string(s: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn lsl_create_streaminfo(
        name: *const ::std::os::raw::c_char,
        type_: *const ::std::os::raw::c_char,
        channel_count: i32,
        nominal_srate: f64,
        channel_format: lsl_channel_format_t,
        source_id: *const ::std::os::raw::c_char,
    ) -> lsl_streaminfo;
}
extern "C" {
    pub fn lsl_destroy_streaminfo(info: lsl_streaminfo);
}
extern "C" {
    pub fn lsl_copy_streaminfo(info: lsl_streaminfo) -> lsl_streaminfo;
}
extern "C" {
    pub fn lsl_get_name(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_type(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_channel_count(info: lsl_streaminfo) -> i32;
}
extern "C" {
    pub fn lsl_get_nominal_srate(info: lsl_streaminfo) -> f64;
}
extern "C" {
    pub fn lsl_get_channel_format(info: lsl_streaminfo) -> lsl_channel_format_t;
}
extern "C" {
    pub fn lsl_get_source_id(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_version(info: lsl_streaminfo) -> i32;
}
extern "C" {
    pub fn lsl_get_created_at(info: lsl_streaminfo) -> f64;
}
extern "C" {
    pub fn lsl_get_uid(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_session_id(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_hostname(info: lsl_streaminfo) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_desc(info: lsl_streaminfo) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_get_xml(info: lsl_streaminfo) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_get_channel_bytes(info: lsl_streaminfo) -> i32;
}
extern "C" {
    pub fn lsl_get_sample_bytes(info: lsl_streaminfo) -> i32;
}
extern "C" {
    pub fn lsl_stream_info_matches_query(
        info: lsl_streaminfo,
        query: *const ::std::os::raw::c_char,
    ) -> i32;
}
extern "C" {
    pub fn lsl_streaminfo_from_xml(xml: *const ::std::os::raw::c_char) -> lsl_streaminfo;
}
extern "C" {
    pub fn lsl_create_outlet(
        info: lsl_streaminfo,
        chunk_size: i32,
        max_buffered: i32,
    ) -> lsl_outlet;
}
extern "C" {
    pub fn lsl_destroy_outlet(out: lsl_outlet);
}
extern "C" {
    pub fn lsl_push_sample_f(out: lsl_outlet, data: *const f32) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_d(out: lsl_outlet, data: *const f64) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_l(out: lsl_outlet, data: *const ::std::os::raw::c_long) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_i(out: lsl_outlet, data: *const i32) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_s(out: lsl_outlet, data: *const i16) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_c(out: lsl_outlet, data: *const ::std::os::raw::c_char) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_str(out: lsl_outlet, data: *mut *const ::std::os::raw::c_char) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_v(out: lsl_outlet, data: *const ::std::os::raw::c_void) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_ft(out: lsl_outlet, data: *const f32, timestamp: f64) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_dt(out: lsl_outlet, data: *const f64, timestamp: f64) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_lt(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_it(out: lsl_outlet, data: *const i32, timestamp: f64) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_st(out: lsl_outlet, data: *const i16, timestamp: f64) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_ct(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_strt(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_vt(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_void,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_ftp(
        out: lsl_outlet,
        data: *const f32,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_dtp(
        out: lsl_outlet,
        data: *const f64,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_ltp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_itp(
        out: lsl_outlet,
        data: *const i32,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_stp(
        out: lsl_outlet,
        data: *const i16,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_ctp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_strtp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_vtp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_void,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_buf(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_buft(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_sample_buftp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_f(
        out: lsl_outlet,
        data: *const f32,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_d(
        out: lsl_outlet,
        data: *const f64,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_l(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_i(
        out: lsl_outlet,
        data: *const i32,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_s(
        out: lsl_outlet,
        data: *const i16,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_c(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_str(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ft(
        out: lsl_outlet,
        data: *const f32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_dt(
        out: lsl_outlet,
        data: *const f64,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_lt(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_it(
        out: lsl_outlet,
        data: *const i32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_st(
        out: lsl_outlet,
        data: *const i16,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ct(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_strt(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ftp(
        out: lsl_outlet,
        data: *const f32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_dtp(
        out: lsl_outlet,
        data: *const f64,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ltp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_itp(
        out: lsl_outlet,
        data: *const i32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_stp(
        out: lsl_outlet,
        data: *const i16,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ctp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_strtp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ftn(
        out: lsl_outlet,
        data: *const f32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_dtn(
        out: lsl_outlet,
        data: *const f64,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ltn(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_itn(
        out: lsl_outlet,
        data: *const i32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_stn(
        out: lsl_outlet,
        data: *const i16,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ctn(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_strtn(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ftnp(
        out: lsl_outlet,
        data: *const f32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_dtnp(
        out: lsl_outlet,
        data: *const f64,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ltnp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_long,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_itnp(
        out: lsl_outlet,
        data: *const i32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_stnp(
        out: lsl_outlet,
        data: *const i16,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_ctnp(
        out: lsl_outlet,
        data: *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_strtnp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_buf(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        data_elements: ::std::os::raw::c_ulong,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_buft(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_buftp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        data_elements: ::std::os::raw::c_ulong,
        timestamp: f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_buftn(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
    ) -> i32;
}
extern "C" {
    pub fn lsl_push_chunk_buftnp(
        out: lsl_outlet,
        data: *mut *const ::std::os::raw::c_char,
        lengths: *const u32,
        data_elements: ::std::os::raw::c_ulong,
        timestamps: *const f64,
        pushthrough: i32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_have_consumers(out: lsl_outlet) -> i32;
}
extern "C" {
    pub fn lsl_wait_for_consumers(out: lsl_outlet, timeout: f64) -> i32;
}
extern "C" {
    pub fn lsl_get_info(out: lsl_outlet) -> lsl_streaminfo;
}
extern "C" {
    pub fn lsl_create_inlet(
        info: lsl_streaminfo,
        max_buflen: i32,
        max_chunklen: i32,
        recover: i32,
    ) -> lsl_inlet;
}
extern "C" {
    pub fn lsl_destroy_inlet(in_: lsl_inlet);
}
extern "C" {
    pub fn lsl_get_fullinfo(in_: lsl_inlet, timeout: f64, ec: *mut i32) -> lsl_streaminfo;
}
extern "C" {
    pub fn lsl_open_stream(in_: lsl_inlet, timeout: f64, ec: *mut i32);
}
extern "C" {
    pub fn lsl_close_stream(in_: lsl_inlet);
}
extern "C" {
    pub fn lsl_time_correction(in_: lsl_inlet, timeout: f64, ec: *mut i32) -> f64;
}
extern "C" {
    pub fn lsl_time_correction_ex(
        in_: lsl_inlet,
        remote_time: *mut f64,
        uncertainty: *mut f64,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_set_postprocessing(in_: lsl_inlet, flags: u32) -> i32;
}
extern "C" {
    pub fn lsl_pull_sample_f(
        in_: lsl_inlet,
        buffer: *mut f32,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_d(
        in_: lsl_inlet,
        buffer: *mut f64,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_l(
        in_: lsl_inlet,
        buffer: *mut ::std::os::raw::c_long,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_i(
        in_: lsl_inlet,
        buffer: *mut i32,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_s(
        in_: lsl_inlet,
        buffer: *mut i16,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_c(
        in_: lsl_inlet,
        buffer: *mut ::std::os::raw::c_char,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_str(
        in_: lsl_inlet,
        buffer: *mut *mut ::std::os::raw::c_char,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_buf(
        in_: lsl_inlet,
        buffer: *mut *mut ::std::os::raw::c_char,
        buffer_lengths: *mut u32,
        buffer_elements: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_sample_v(
        in_: lsl_inlet,
        buffer: *mut ::std::os::raw::c_void,
        buffer_bytes: i32,
        timeout: f64,
        ec: *mut i32,
    ) -> f64;
}
extern "C" {
    pub fn lsl_pull_chunk_f(
        in_: lsl_inlet,
        data_buffer: *mut f32,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_d(
        in_: lsl_inlet,
        data_buffer: *mut f64,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_l(
        in_: lsl_inlet,
        data_buffer: *mut ::std::os::raw::c_long,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_i(
        in_: lsl_inlet,
        data_buffer: *mut i32,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_s(
        in_: lsl_inlet,
        data_buffer: *mut i16,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_c(
        in_: lsl_inlet,
        data_buffer: *mut ::std::os::raw::c_char,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_str(
        in_: lsl_inlet,
        data_buffer: *mut *mut ::std::os::raw::c_char,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_pull_chunk_buf(
        in_: lsl_inlet,
        data_buffer: *mut *mut ::std::os::raw::c_char,
        lengths_buffer: *mut u32,
        timestamp_buffer: *mut f64,
        data_buffer_elements: ::std::os::raw::c_ulong,
        timestamp_buffer_elements: ::std::os::raw::c_ulong,
        timeout: f64,
        ec: *mut i32,
    ) -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn lsl_samples_available(in_: lsl_inlet) -> u32;
}
extern "C" {
    pub fn lsl_was_clock_reset(in_: lsl_inlet) -> u32;
}
extern "C" {
    pub fn lsl_smoothing_halftime(in_: lsl_inlet, value: f32) -> i32;
}
extern "C" {
    pub fn lsl_first_child(e: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_last_child(e: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_next_sibling(e: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_previous_sibling(e: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_parent(e: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_child(e: lsl_xml_ptr, name: *const ::std::os::raw::c_char) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_next_sibling_n(e: lsl_xml_ptr, name: *const ::std::os::raw::c_char) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_previous_sibling_n(
        e: lsl_xml_ptr,
        name: *const ::std::os::raw::c_char,
    ) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_empty(e: lsl_xml_ptr) -> i32;
}
extern "C" {
    pub fn lsl_is_text(e: lsl_xml_ptr) -> i32;
}
extern "C" {
    pub fn lsl_name(e: lsl_xml_ptr) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_value(e: lsl_xml_ptr) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_child_value(e: lsl_xml_ptr) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_child_value_n(
        e: lsl_xml_ptr,
        name: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn lsl_append_child_value(
        e: lsl_xml_ptr,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_prepend_child_value(
        e: lsl_xml_ptr,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_set_child_value(
        e: lsl_xml_ptr,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> i32;
}
extern "C" {
    pub fn lsl_set_name(e: lsl_xml_ptr, rhs: *const ::std::os::raw::c_char) -> i32;
}
extern "C" {
    pub fn lsl_set_value(e: lsl_xml_ptr, rhs: *const ::std::os::raw::c_char) -> i32;
}
extern "C" {
    pub fn lsl_append_child(e: lsl_xml_ptr, name: *const ::std::os::raw::c_char) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_prepend_child(e: lsl_xml_ptr, name: *const ::std::os::raw::c_char) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_append_copy(e: lsl_xml_ptr, e2: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_prepend_copy(e: lsl_xml_ptr, e2: lsl_xml_ptr) -> lsl_xml_ptr;
}
extern "C" {
    pub fn lsl_remove_child_n(e: lsl_xml_ptr, name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn lsl_remove_child(e: lsl_xml_ptr, e2: lsl_xml_ptr);
}
extern "C" {
    pub fn lsl_create_continuous_resolver(forget_after: f64) -> lsl_continuous_resolver;
}
extern "C" {
    pub fn lsl_create_continuous_resolver_byprop(
        prop: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        forget_after: f64,
    ) -> lsl_continuous_resolver;
}
extern "C" {
    pub fn lsl_create_continuous_resolver_bypred(
        pred: *const ::std::os::raw::c_char,
        forget_after: f64,
    ) -> lsl_continuous_resolver;
}
extern "C" {
    pub fn lsl_resolver_results(
        res: lsl_continuous_resolver,
        buffer: *mut lsl_streaminfo,
        buffer_elements: u32,
    ) -> i32;
}
extern "C" {
    pub fn lsl_destroy_continuous_resolver(res: lsl_continuous_resolver);
}
